/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AccountRulesV2 {
  export type AccountDataStruct = {
    orgId: BigNumberish;
    account: AddressLike;
    roleId: BytesLike;
    dataHash: BytesLike;
    active: boolean;
  };

  export type AccountDataStructOutput = [
    orgId: bigint,
    account: string,
    roleId: string,
    dataHash: string,
    active: boolean
  ] & {
    orgId: bigint;
    account: string;
    roleId: string;
    dataHash: string;
    active: boolean;
  };
}

export interface AccountRulesV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAccount"
      | "addLocalAccount"
      | "deleteAccount"
      | "deleteLocalAccount"
      | "getAccount"
      | "getAccountTargetAccess"
      | "getAccounts"
      | "getAccountsByOrg"
      | "getNumberOfAccounts"
      | "getNumberOfAccountsByOrg"
      | "getNumberOfRestrictedAccounts"
      | "getNumberOfRestrictedSmartContracts"
      | "getRestrictedAccounts"
      | "getRestrictedSmartContracts"
      | "getRoleAdmin"
      | "getSmartContractSenderAccess"
      | "grantRole"
      | "hasRole"
      | "isAccountActive"
      | "renounceRole"
      | "revokeRole"
      | "setAccountTargetAccess"
      | "setSmartContractSenderAccess"
      | "transactionAllowed"
      | "updateLocalAccount"
      | "updateLocalAccountStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountAdded"
      | "AccountDeleted"
      | "AccountStatusUpdated"
      | "AccountTargetAccessUpdated"
      | "AccountUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SmartContractSenderAccessUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAccount",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addLocalAccount",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteLocalAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountTargetAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccounts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountsByOrg",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfAccounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfAccountsByOrg",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfRestrictedAccounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfRestrictedSmartContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRestrictedAccounts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRestrictedSmartContracts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSmartContractSenderAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAccountActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAccountTargetAccess",
    values: [AddressLike, boolean, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setSmartContractSenderAccess",
    values: [AddressLike, boolean, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionAllowed",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLocalAccount",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLocalAccountStatus",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "addAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addLocalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteLocalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccountTargetAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountsByOrg",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfAccountsByOrg",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfRestrictedAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfRestrictedSmartContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRestrictedAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRestrictedSmartContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmartContractSenderAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAccountActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAccountTargetAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSmartContractSenderAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactionAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLocalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLocalAccountStatus",
    data: BytesLike
  ): Result;
}

export namespace AccountAddedEvent {
  export type InputTuple = [
    account: AddressLike,
    orgId: BigNumberish,
    roleId: BytesLike,
    dataHash: BytesLike
  ];
  export type OutputTuple = [
    account: string,
    orgId: bigint,
    roleId: string,
    dataHash: string
  ];
  export interface OutputObject {
    account: string;
    orgId: bigint;
    roleId: string;
    dataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountDeletedEvent {
  export type InputTuple = [account: AddressLike, orgId: BigNumberish];
  export type OutputTuple = [account: string, orgId: bigint];
  export interface OutputObject {
    account: string;
    orgId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountStatusUpdatedEvent {
  export type InputTuple = [
    account: AddressLike,
    orgId: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [account: string, orgId: bigint, active: boolean];
  export interface OutputObject {
    account: string;
    orgId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountTargetAccessUpdatedEvent {
  export type InputTuple = [
    account: AddressLike,
    restricted: boolean,
    allowedTargets: AddressLike[]
  ];
  export type OutputTuple = [
    account: string,
    restricted: boolean,
    allowedTargets: string[]
  ];
  export interface OutputObject {
    account: string;
    restricted: boolean;
    allowedTargets: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountUpdatedEvent {
  export type InputTuple = [
    account: AddressLike,
    orgId: BigNumberish,
    roleId: BytesLike,
    dataHash: BytesLike
  ];
  export type OutputTuple = [
    account: string,
    orgId: bigint,
    roleId: string,
    dataHash: string
  ];
  export interface OutputObject {
    account: string;
    orgId: bigint;
    roleId: string;
    dataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SmartContractSenderAccessUpdatedEvent {
  export type InputTuple = [
    smartContract: AddressLike,
    restricted: boolean,
    allowedSenders: AddressLike[]
  ];
  export type OutputTuple = [
    smartContract: string,
    restricted: boolean,
    allowedSenders: string[]
  ];
  export interface OutputObject {
    smartContract: string;
    restricted: boolean;
    allowedSenders: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccountRulesV2 extends BaseContract {
  connect(runner?: ContractRunner | null): AccountRulesV2;
  waitForDeployment(): Promise<this>;

  interface: AccountRulesV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAccount: TypedContractMethod<
    [
      account: AddressLike,
      orgId: BigNumberish,
      roleId: BytesLike,
      dataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  addLocalAccount: TypedContractMethod<
    [account: AddressLike, roleId: BytesLike, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  deleteAccount: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  deleteLocalAccount: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  getAccount: TypedContractMethod<
    [account: AddressLike],
    [AccountRulesV2.AccountDataStructOutput],
    "view"
  >;

  getAccountTargetAccess: TypedContractMethod<
    [account: AddressLike],
    [[boolean, string[]] & { restricted: boolean }],
    "view"
  >;

  getAccounts: TypedContractMethod<
    [pageNumber: BigNumberish, pageSize: BigNumberish],
    [AccountRulesV2.AccountDataStructOutput[]],
    "view"
  >;

  getAccountsByOrg: TypedContractMethod<
    [orgId: BigNumberish, pageNumber: BigNumberish, pageSize: BigNumberish],
    [AccountRulesV2.AccountDataStructOutput[]],
    "view"
  >;

  getNumberOfAccounts: TypedContractMethod<[], [bigint], "view">;

  getNumberOfAccountsByOrg: TypedContractMethod<
    [orgId: BigNumberish],
    [bigint],
    "view"
  >;

  getNumberOfRestrictedAccounts: TypedContractMethod<[], [bigint], "view">;

  getNumberOfRestrictedSmartContracts: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getRestrictedAccounts: TypedContractMethod<
    [pageNumber: BigNumberish, pageSize: BigNumberish],
    [string[]],
    "view"
  >;

  getRestrictedSmartContracts: TypedContractMethod<
    [pageNumber: BigNumberish, pageSize: BigNumberish],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSmartContractSenderAccess: TypedContractMethod<
    [smartContract: AddressLike],
    [[boolean, string[]] & { restricted: boolean }],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isAccountActive: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAccountTargetAccess: TypedContractMethod<
    [account: AddressLike, restricted: boolean, allowedTargets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setSmartContractSenderAccess: TypedContractMethod<
    [
      smartContract: AddressLike,
      restricted: boolean,
      allowedSenders: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  transactionAllowed: TypedContractMethod<
    [
      sender: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      gasPrice: BigNumberish,
      gasLimit: BigNumberish,
      payload: BytesLike
    ],
    [boolean],
    "view"
  >;

  updateLocalAccount: TypedContractMethod<
    [account: AddressLike, roleId: BytesLike, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  updateLocalAccountStatus: TypedContractMethod<
    [account: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAccount"
  ): TypedContractMethod<
    [
      account: AddressLike,
      orgId: BigNumberish,
      roleId: BytesLike,
      dataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLocalAccount"
  ): TypedContractMethod<
    [account: AddressLike, roleId: BytesLike, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteAccount"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteLocalAccount"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccount"
  ): TypedContractMethod<
    [account: AddressLike],
    [AccountRulesV2.AccountDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccountTargetAccess"
  ): TypedContractMethod<
    [account: AddressLike],
    [[boolean, string[]] & { restricted: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccounts"
  ): TypedContractMethod<
    [pageNumber: BigNumberish, pageSize: BigNumberish],
    [AccountRulesV2.AccountDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccountsByOrg"
  ): TypedContractMethod<
    [orgId: BigNumberish, pageNumber: BigNumberish, pageSize: BigNumberish],
    [AccountRulesV2.AccountDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNumberOfAccounts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNumberOfAccountsByOrg"
  ): TypedContractMethod<[orgId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNumberOfRestrictedAccounts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNumberOfRestrictedSmartContracts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRestrictedAccounts"
  ): TypedContractMethod<
    [pageNumber: BigNumberish, pageSize: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRestrictedSmartContracts"
  ): TypedContractMethod<
    [pageNumber: BigNumberish, pageSize: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSmartContractSenderAccess"
  ): TypedContractMethod<
    [smartContract: AddressLike],
    [[boolean, string[]] & { restricted: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAccountActive"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAccountTargetAccess"
  ): TypedContractMethod<
    [account: AddressLike, restricted: boolean, allowedTargets: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSmartContractSenderAccess"
  ): TypedContractMethod<
    [
      smartContract: AddressLike,
      restricted: boolean,
      allowedSenders: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transactionAllowed"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      gasPrice: BigNumberish,
      gasLimit: BigNumberish,
      payload: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateLocalAccount"
  ): TypedContractMethod<
    [account: AddressLike, roleId: BytesLike, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateLocalAccountStatus"
  ): TypedContractMethod<
    [account: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccountAdded"
  ): TypedContractEvent<
    AccountAddedEvent.InputTuple,
    AccountAddedEvent.OutputTuple,
    AccountAddedEvent.OutputObject
  >;
  getEvent(
    key: "AccountDeleted"
  ): TypedContractEvent<
    AccountDeletedEvent.InputTuple,
    AccountDeletedEvent.OutputTuple,
    AccountDeletedEvent.OutputObject
  >;
  getEvent(
    key: "AccountStatusUpdated"
  ): TypedContractEvent<
    AccountStatusUpdatedEvent.InputTuple,
    AccountStatusUpdatedEvent.OutputTuple,
    AccountStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AccountTargetAccessUpdated"
  ): TypedContractEvent<
    AccountTargetAccessUpdatedEvent.InputTuple,
    AccountTargetAccessUpdatedEvent.OutputTuple,
    AccountTargetAccessUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AccountUpdated"
  ): TypedContractEvent<
    AccountUpdatedEvent.InputTuple,
    AccountUpdatedEvent.OutputTuple,
    AccountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SmartContractSenderAccessUpdated"
  ): TypedContractEvent<
    SmartContractSenderAccessUpdatedEvent.InputTuple,
    SmartContractSenderAccessUpdatedEvent.OutputTuple,
    SmartContractSenderAccessUpdatedEvent.OutputObject
  >;

  filters: {
    "AccountAdded(address,uint256,bytes32,bytes32)": TypedContractEvent<
      AccountAddedEvent.InputTuple,
      AccountAddedEvent.OutputTuple,
      AccountAddedEvent.OutputObject
    >;
    AccountAdded: TypedContractEvent<
      AccountAddedEvent.InputTuple,
      AccountAddedEvent.OutputTuple,
      AccountAddedEvent.OutputObject
    >;

    "AccountDeleted(address,uint256)": TypedContractEvent<
      AccountDeletedEvent.InputTuple,
      AccountDeletedEvent.OutputTuple,
      AccountDeletedEvent.OutputObject
    >;
    AccountDeleted: TypedContractEvent<
      AccountDeletedEvent.InputTuple,
      AccountDeletedEvent.OutputTuple,
      AccountDeletedEvent.OutputObject
    >;

    "AccountStatusUpdated(address,uint256,bool)": TypedContractEvent<
      AccountStatusUpdatedEvent.InputTuple,
      AccountStatusUpdatedEvent.OutputTuple,
      AccountStatusUpdatedEvent.OutputObject
    >;
    AccountStatusUpdated: TypedContractEvent<
      AccountStatusUpdatedEvent.InputTuple,
      AccountStatusUpdatedEvent.OutputTuple,
      AccountStatusUpdatedEvent.OutputObject
    >;

    "AccountTargetAccessUpdated(address,bool,address[])": TypedContractEvent<
      AccountTargetAccessUpdatedEvent.InputTuple,
      AccountTargetAccessUpdatedEvent.OutputTuple,
      AccountTargetAccessUpdatedEvent.OutputObject
    >;
    AccountTargetAccessUpdated: TypedContractEvent<
      AccountTargetAccessUpdatedEvent.InputTuple,
      AccountTargetAccessUpdatedEvent.OutputTuple,
      AccountTargetAccessUpdatedEvent.OutputObject
    >;

    "AccountUpdated(address,uint256,bytes32,bytes32)": TypedContractEvent<
      AccountUpdatedEvent.InputTuple,
      AccountUpdatedEvent.OutputTuple,
      AccountUpdatedEvent.OutputObject
    >;
    AccountUpdated: TypedContractEvent<
      AccountUpdatedEvent.InputTuple,
      AccountUpdatedEvent.OutputTuple,
      AccountUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SmartContractSenderAccessUpdated(address,bool,address[])": TypedContractEvent<
      SmartContractSenderAccessUpdatedEvent.InputTuple,
      SmartContractSenderAccessUpdatedEvent.OutputTuple,
      SmartContractSenderAccessUpdatedEvent.OutputObject
    >;
    SmartContractSenderAccessUpdated: TypedContractEvent<
      SmartContractSenderAccessUpdatedEvent.InputTuple,
      SmartContractSenderAccessUpdatedEvent.OutputTuple,
      SmartContractSenderAccessUpdatedEvent.OutputObject
    >;
  };
}
