/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { AdminProxy, AdminProxyInterface } from "../AdminProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "source",
        type: "address",
      },
    ],
    name: "isAuthorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AdminProxy__factory {
  static readonly abi = _abi;
  static createInterface(): AdminProxyInterface {
    return new Interface(_abi) as AdminProxyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): AdminProxy {
    return new Contract(address, _abi, runner) as unknown as AdminProxy;
  }
}
