/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Governable, GovernableInterface } from "../Governable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "UnauthorizedAccess",
    type: "error",
  },
  {
    inputs: [],
    name: "admins",
    outputs: [
      {
        internalType: "contract AdminProxy",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Governable__factory {
  static readonly abi = _abi;
  static createInterface(): GovernableInterface {
    return new Interface(_abi) as GovernableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Governable {
    return new Contract(address, _abi, runner) as unknown as Governable;
  }
}
